name: time_tracker
description: A time tracking app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For date formatting
  intl: ^0.18.1
  
  # For state management
  provider: ^6.1.1
  
  # For collection operations
  collection: ^1.18.0
  
  # For local storage
  localstorage: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true